server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route vers Product Service
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**

        # Route vers Payment Service
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/ws/**

        # Route vers Orchestrator Service
        - id: orchestrator-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/orchestrator/**

        # Route vers Customer Portal (GraphQL)
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/graphiql/**, /graphql/**